[tool.poetry]
name = "calmlib"
version = "0.2.1" # fix version variable loading..
description = "Calmlib"
authors = ["Reliable Magician <petr.b.lavrov@gmail.com>"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Development Status :: 4 - Beta",
    "Environment :: Other Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.4"
toml = "*"
pytz = "*"
tqdm = "*"
pyperclip = "*"
mongoengine = "^0.27.0"
loguru = "*"
# defaultenv = { git = "https://github.com/bobuk/defaultenv.git", branch ="master", optional = true }
# bmmb = { git = "https://github.com/calmmage/bot_me_maybe.git", branch ="main", optional = true }
gpt_kit = { git = "https://github.com/calmmage/gpt_kit.git", branch = "main", optional = true }

[tool.poetry.extras]
full = ["dropbox", "protobuf", "pandas", "seaborn", "defaultenv", "bmmb",
    "gpt_kit", "httpx", "pydantic", "bokeh", "click", "fastapi", "nltk"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Home" = "https://github.com/calmmage/calmlib"
